// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbvggdSUSkXohXov0cC0xWoV-Bs9jjMdg',
    appId: '1:867054067354:web:1d43cbd0c762dcf4160923',
    messagingSenderId: '867054067354',
    projectId: 'ecommercestore-203d7',
    authDomain: 'ecommercestore-203d7.firebaseapp.com',
    databaseURL: 'https://ecommercestore-203d7-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercestore-203d7.firebasestorage.app',
    measurementId: 'G-3VVCMKS391',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJWwmImm4t2cpklqAB2ukHitmPvWZ7BJM',
    appId: '1:867054067354:android:22a750db16d3c53b160923',
    messagingSenderId: '867054067354',
    projectId: 'ecommercestore-203d7',
    databaseURL: 'https://ecommercestore-203d7-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercestore-203d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtFr51jaYeduNdCFLS1LRTVLUeUcuBOHc',
    appId: '1:867054067354:ios:7abd664f1cc0ff6e160923',
    messagingSenderId: '867054067354',
    projectId: 'ecommercestore-203d7',
    databaseURL: 'https://ecommercestore-203d7-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercestore-203d7.firebasestorage.app',
    iosClientId: '867054067354-0dk0p5etnsp4hpb41p98rr784p94692g.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtFr51jaYeduNdCFLS1LRTVLUeUcuBOHc',
    appId: '1:867054067354:ios:7abd664f1cc0ff6e160923',
    messagingSenderId: '867054067354',
    projectId: 'ecommercestore-203d7',
    databaseURL: 'https://ecommercestore-203d7-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercestore-203d7.firebasestorage.app',
    iosClientId: '867054067354-0dk0p5etnsp4hpb41p98rr784p94692g.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqxLx0Pni2_h_NTbzzLuKVWDwSpFSAjP8',
    appId: '1:867054067354:web:04dad7d4074021f0160923',
    messagingSenderId: '867054067354',
    projectId: 'ecommercestore-203d7',
    authDomain: 'ecommercestore-203d7.firebaseapp.com',
    databaseURL: 'https://ecommercestore-203d7-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercestore-203d7.firebasestorage.app',
    measurementId: 'G-SQVK7P2VJB',
  );
}
